app_name: "fusion-framework"
server_ip: "0.0.0.0"
server_port: "3000"
dsn_type: "mysql"
dsn: "mysql://restapi:pass_to_restapi@/restapi?parseTime=true"
jwt_signing_key: "someSecretUtf832CharsForStrongValidJwtCryptography"
