app_name: "fusion-framework"
db_type: "mysql"
dsn: "mysql://appname:pass_to_appname@/appname?parseTime=true"
jwt_signing_key: "someSecretUtf832CharsForStrongValidJwtCryptography"
jwt_expiration: 2
mail_smtphost: "smtp.xxxxx.xxxx"
mail_smtpport: "587"
mail_username: "xxxxxxxxxxxx@xxxxxxxxx.xxxx"
mail_password: "xxxxxxxxxx"
app_fqdn: "localhost"
http_entrypoint: "127.0.0.1:3000"
webserv_name: "fusion-framework"
google_credential_file: "./data/credential.json"
google_redirect_path: "/oauth/googleuser"
app_secret_key: "someSecretUtf8by32CharsForStrongValidJwtCryptography"
biz_name: "xxxxxxxxxx"
biz_shortname: "xxxxxxxxxxxx"
biz_email: ""
biz_phone: ""
biz_phone2: ""
biz_logo: "favicon.ico"
